### ISSUE TITLE
Bouncing-circles

### ISSUE THREAD

**Issue by VWang1111** [tinaxye/desinv23-hw6#1]
The bouncing circles visual indicator is a bit difficult to understand. I tried checking the code with only 1 circle and no visual indicator was there. When there were 2 circles, the visual indicator only appeared when the other circle hit the wall. Was that the intention? Maybe a comment in the code would be helpful to understand.

**Comment by tinaxye** [comment]
Hi Victor, every time a circle hits a boundary, all the circles are supposed to "jiggle".  I'll definitely look into why it doesn't work for one circle though. Thank you!
